services:
  db:
    image: postgres:13
    container_name: pharmahub_db
    restart: always
    environment:
      POSTGRES_USER: pharma_user
      POSTGRES_PASSWORD: pharma_password
      POSTGRES_DB: pharmahub
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
